using LocalCacheChecker.ApiModels;
using LocalCacheChecker.SaveModels;
using System.Text.Json.Serialization;

namespace LocalCacheChecker.SerializerContext {

    [JsonSerializable ( typeof ( FranchiseImageModel ) )]
    [JsonSerializable ( typeof ( FranchiseModel ) )]
    [JsonSerializable ( typeof ( FranchiseReleasesItemModel ) )]
    [JsonSerializable ( typeof ( FranchiseReleasesModel ) )]
    [JsonSerializable ( typeof ( IntegerValueItem ) )]
    [JsonSerializable ( typeof ( ReleaseDataModel ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelAgeRating ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelGenre ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelPoster ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelPublishDay ) )]
    [JsonSerializable ( typeof ( ReleaseDataNameModel ) )]
    [JsonSerializable ( typeof ( ReleaseDataSeasonModel ) )]
    [JsonSerializable ( typeof ( ReleaseDataTypeModel ) )]
    [JsonSerializable ( typeof ( ReleaseEpisodeModel ) )]
    [JsonSerializable ( typeof ( ReleaseMemberModel ) )]
    [JsonSerializable ( typeof ( ReleaseMetaModel ) )]
    [JsonSerializable ( typeof ( ReleaseOnlyCollectionsModel ) )]
    [JsonSerializable ( typeof ( ReleasePaginationModel ) )]
    [JsonSerializable ( typeof ( ReleasesModel ) )]
    [JsonSerializable ( typeof ( ReleaseTorrentModel ) )]
    [JsonSerializable ( typeof ( ScheduleReleaseIdModel ) )]
    [JsonSerializable ( typeof ( ScheduleReleaseModel ) )]
    [JsonSerializable ( typeof ( StringValueItem ) )]
    [JsonSerializable ( typeof ( TimeRange ) )]
    [JsonSerializable ( typeof ( MetadataModel ) )]
    [JsonSerializable ( typeof ( List<ReleaseSaveEpisodeModel> ) )]
    [JsonSerializable ( typeof ( List<ReleaseSaveModel> ) )]
    [JsonSerializable ( typeof ( List<ReleaseSeriesSaveModel> ) )]
    [JsonSerializable ( typeof ( List<ReleaseTorrentSaveModel> ) )]
    [JsonSerializable ( typeof ( IEnumerable<ReleaseSaveEpisodeModel> ) )]
    [JsonSerializable ( typeof ( IEnumerable<ReleaseSaveModel> ) )]
    [JsonSerializable ( typeof ( IEnumerable<ReleaseSeriesSaveModel> ) )]
    [JsonSerializable ( typeof ( IEnumerable<ReleaseTorrentSaveModel> ) )]
    [JsonSerializable ( typeof ( ReleaseSaveEpisodeModel ) )]
    [JsonSerializable ( typeof ( ReleaseSaveModel ) )]
    [JsonSerializable ( typeof ( ReleaseSeriesSaveModel ) )]
    [JsonSerializable ( typeof ( ReleaseTorrentSaveModel ) )]
    [JsonSerializable ( typeof ( TypesResultModel ) )]
    [JsonSerializable ( typeof ( IEnumerable<IntegerValueItem> ) )]
    [JsonSerializable ( typeof ( IEnumerable<StringValueItem> ) )]
    [JsonSerializable ( typeof ( Dictionary<string, int> ) )]
    [JsonSourceGenerationOptions ( PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, WriteIndented = false )]
    internal partial class ApiModelSerializerContext : JsonSerializerContext {
    }

    [JsonSerializable ( typeof ( FranchiseImageModel ) )]
    [JsonSerializable ( typeof ( FranchiseModel ) )]
    [JsonSerializable ( typeof ( IEnumerable<FranchiseModel> ) )]
    [JsonSerializable ( typeof ( FranchiseReleasesItemModel ) )]
    [JsonSerializable ( typeof ( FranchiseReleasesModel ) )]
    [JsonSerializable ( typeof ( IntegerValueItem ) )]
    [JsonSerializable ( typeof ( ReleaseDataModel ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelAgeRating ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelGenre ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelPoster ) )]
    [JsonSerializable ( typeof ( ReleaseDataModelPublishDay ) )]
    [JsonSerializable ( typeof ( ReleaseDataNameModel ) )]
    [JsonSerializable ( typeof ( ReleaseDataSeasonModel ) )]
    [JsonSerializable ( typeof ( ReleaseDataTypeModel ) )]
    [JsonSerializable ( typeof ( ReleaseEpisodeModel ) )]
    [JsonSerializable ( typeof ( ReleaseMemberModel ) )]
    [JsonSerializable ( typeof ( ReleaseMetaModel ) )]
    [JsonSerializable ( typeof ( ReleaseOnlyCollectionsModel ) )]
    [JsonSerializable ( typeof ( ReleasePaginationModel ) )]
    [JsonSerializable ( typeof ( ReleasesModel ) )]
    [JsonSerializable ( typeof ( ReleaseTorrentModel ) )]
    [JsonSerializable ( typeof ( ScheduleReleaseIdModel ) )]
    [JsonSerializable ( typeof ( IEnumerable<ScheduleReleaseModel> ) )]
    [JsonSerializable ( typeof ( ScheduleReleaseModel ) )]
    [JsonSerializable ( typeof ( ScheduleReleaseModel ) )]
    [JsonSerializable ( typeof ( StringValueItem ) )]
    [JsonSerializable ( typeof ( TimeRange ) )]
    [JsonSerializable ( typeof ( MetadataModel ) )]
    [JsonSerializable ( typeof ( ReleaseSaveEpisodeModel ) )]
    [JsonSerializable ( typeof ( ReleaseSaveModel ) )]
    [JsonSerializable ( typeof ( IEnumerable<ReleaseSaveModel> ) )]
    [JsonSerializable ( typeof ( ReleaseSeriesSaveModel ) )]
    [JsonSerializable ( typeof ( ReleaseTorrentSaveModel ) )]
    [JsonSerializable ( typeof ( TypesResultModel ) )]
    [JsonSerializable ( typeof ( IEnumerable<IntegerValueItem> ) )]
    [JsonSerializable ( typeof ( IEnumerable<StringValueItem> ) )]
    [JsonSerializable ( typeof ( Dictionary<string, int> ) )]
    [JsonSourceGenerationOptions ( PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower )]
    internal partial class ReadApiModelSerializerContext : JsonSerializerContext {
    }


}
