name: Full synchronization

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CACHE_PATH: cache

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish -r win-x64 -c Release -p:PublishAot=false --self-contained true -p:PublishSingleFile=true src/LocalCacheChecker.csproj

    - name: Run synchronization
      run: |
        cp src/bin/Release/net8.0/win-x64/publish/LocalCacheChecker.exe LocalCacheChecker.exe
        LocalCacheChecker.exe -all
